### ISSUE TITLE
Add picture via uploadimage does not update model

### ISSUE THREAD

**Issue by lukashinsch** [esvit/ng-ckeditor#71]
Hi,
When I paste/drop an image via uploadimage plugin the model does not get updated.
This seems to be due to the listener on the "pasteState" event being commented-out (see https://github.com/esvit/ng-ckeditor/blob/master/ng-ckeditor.js#L117). When I activate the line everything works fine.
Any reason why this was removed?
Thanks.

**Comment by kierenj** [comment]
Inappropriate place to ask perhaps, but how are you using the plugin with ng-ckeditor?  Other issues on GH talk about a 'lib' folder, which doesn't exist, and adding a 'plugins' folder to my ng-ckeditor folder doesn't do anything; ckeditor still tries to download the plugin from the official site (and fails).
